### ISSUE TITLE
In line 90, it shows an error:  "NameError: name 'plt' is not defined"

### ISSUE THREAD

**Issue by HamadAndrabi** [krishnaik06/Car-Price-Prediction#16]
This can be fixed by importing matplotlib at the beginning of the code block.
"import matplotlib.pyplot as plt"

**Comment by julienawonga** [comment]
Write this import matplotlib.pyplot as plt at the top of your code

**Comment by Abu-bakr-Siddiqh** [comment]
while importing the matplotlib...... 
import as  "import matplotlib.pyplot as plt"
